Implemented draft of adaptive main page.
js-tasks-ru/htmlcss-20230530_amozalev pull request #13
Opened 2023-06-17 18:09 UTC by amozalev

2023-06-17 18:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-18 21:24 UTC, GSemikozov requested changes

2023-06-18 21:24 UTC, GSemikozov commented on components/card/card.css
> +        background: var(--white);
чуть выше ведь все эти свойства мы уже задали, получается просто дублирование кода?)

2023-06-19 21:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-19 21:07 UTC, GSemikozov approved these changes

2023-06-19 21:07 UTC, merged