Implemented radio button.
js-tasks-ru/htmlcss-20230530_amozalev pull request #19
Opened 2023-06-26 21:03 UTC by amozalev

2023-06-26 21:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-26 22:55 UTC, GSemikozov requested changes

2023-06-26 22:55 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    position: relative;;
лишняя `;`

2023-06-26 22:55 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    opacity: 0;
см МР с чекбоксом

2023-06-27 18:13 UTC, amozalev commented on 07-lection5/02-radio/radio.css
> +    opacity: 0;
исправил

2023-07-01 15:14 UTC, amozalev commented on 07-lection5/02-radio/radio.css
> +    position: relative;;
убрал

2023-07-01 15:15 UTC, amozalev commented on 07-lection5/02-radio/radio.css
> +    opacity: 0;
и ещё раз исправил)

2023-07-02 03:11 UTC, GSemikozov approved these changes

2023-07-02 03:11 UTC, merged