Implemented input.
js-tasks-ru/htmlcss-20230530_amozalev pull request #21
Opened 2023-06-27 21:24 UTC by amozalev

2023-06-27 21:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-27 21:33 UTC, amozalev commented
1. Не понял из описания, что подразумевается для _success:focus, _invalid:focus. Я понимаю так, что если после того, как фокус попадает на поле (не важно success или invalid), то поле теряет соответствующий стиль и приобретает стиль для focus.
2. Не понял про задание со звёздочкой про disabled. В моей реализации я использую обычный input и просто исходный disabled. В чём ошибаюсь?
3. Сделал dropdown, но понятно, что это не dropdown. Тут как раз использовал disabled, чтобы выключить input. Нужно было select стилизовать?

2023-06-30 20:35 UTC, GSemikozov requested changes

2023-06-30 20:35 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <span class="input__label">Label</span>
именно это - `label`

2023-06-30 20:35 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="input__control">
а здесь заворачиваем в обычный div

2023-06-30 20:35 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <svg class="input__icon icon">
+ input__icon_success
=> обе иконки состояния присутствуют в разметке сразу

2023-06-30 20:35 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="input input_dropdown">
это лишнее

2023-06-30 20:35 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__label {
не хватает margin-bottom

2023-06-30 20:35 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__icon {
+ display: none

2023-07-01 15:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-01 15:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-01 15:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-01 15:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-01 19:50 UTC, amozalev commented on 07-lection5/04-input/input.css
> +.input__label {
есть же gap: 5px. зачем margin-bottom?

2023-07-01 19:50 UTC, amozalev commented on 07-lection5/04-input/index.html
> +        <div class="input input_dropdown">
удалил

2023-07-01 19:50 UTC, amozalev commented on 07-lection5/04-input/index.html
> +            <label class="input__control">
исправил

2023-07-01 19:51 UTC, amozalev commented on 07-lection5/04-input/index.html
> +            <span class="input__label">Label</span>
исправил

2023-07-01 19:57 UTC, amozalev commented on 07-lection5/04-input/input.css
> +.input__icon {
добавил

2023-07-01 20:02 UTC, amozalev commented on 07-lection5/04-input/index.html
> +                <svg class="input__icon icon">
добавил везде

2023-07-01 20:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-01 20:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-02 03:12 UTC, GSemikozov approved these changes, later dismissed

2023-07-02 03:12 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-07-02 10:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-05 20:48 UTC, GSemikozov approved these changes

2023-07-05 20:48 UTC, merged