Accordion
js-tasks-ru/htmlcss-20230530_amozalev pull request #5
Opened 2023-06-08 22:06 UTC by amozalev

2023-06-08 22:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-09 14:06 UTC, GSemikozov requested changes

2023-06-09 14:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 579px;
лишнее ограничение

2023-06-09 14:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
высоту не стоит фиксировать

2023-06-09 14:06 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
это элемент аккордиона accordion__item, коих здесь по дизайну должно быть 3

2023-06-09 14:06 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__item">— Сдаётся мне, Братец Кролик, на этот раз я тебя поймал. Может, я и ошибаюсь,
accordion__item -> accordion__text

2023-06-10 12:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-10 12:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-10 12:39 UTC, amozalev commented on 03-lection1/02-accordion/accordion.css
> +    width: 579px;
исправил

2023-06-10 12:39 UTC, amozalev commented on 03-lection1/02-accordion/accordion.css
> +    height: 72px;
исправил

2023-06-10 13:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-10 13:13 UTC, amozalev commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
да, не понял изначально. исправил

2023-06-10 13:16 UTC, amozalev commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__item">— Сдаётся мне, Братец Кролик, на этот раз я тебя поймал. Может, я и ошибаюсь,
исправил

2023-06-10 13:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-10 13:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-11 20:27 UTC, GSemikozov approved these changes

2023-06-11 20:27 UTC, merged